/* eslint-disable global-require */
export default ({
  ft1: require('./data/feature-borders.svg').default,
  ft2: require('./data/feature-war.svg').default,
  ft3: require('./data/feature-invention.svg').default,
  ft4: require('./data/feature-research.svg').default,
  ft5: require('./data/feature-demography.svg').default,
  ft6: require('./data/feature-language.svg').default,
  ft7: require('./data/feature-settings.svg').default,
  ft8: require('./data/feature-export.svg').default,
  ft9: require('./data/feature-religion.svg').default,
  ft10: require('./data/feature-nations.svg').default,
  ft11: require('./data/feature-disaster.svg').default,
  ft12: require('./data/feature-expedition.svg').default,

  //  pic0: require('./data/preview-greymapsimple.png').default,
  pic1: require('./data/preview-worldmapsimple.png').default,
  pic2: require('./data/preview-inventionmapsimple.png').default,
  pic3: require('./data/preview-exportmap.png').default,
  pic4: require('./data/preview-researchmap.png').default,
  pic5: require('./data/preview-storytellingmap.png').default,
  //  pic3: require('./data/export2.png').default,
  pic6: require('./data/preview-warmapsimple.png').default,
  pic7: require('./data/preview-populationmapsimple.png').default,
  pic8: require('./data/preview-religionmapsimple.png').default,
  pic9: require('./data/preview-languagemapsimple.png').default,
  pic10: require('./data/preview-racemapsimple.png').default,
  pic11: require('./data/preview-accidentmapsimple.png').default,
  pic12: require('./data/preview-expeditionmapsimple.png').default,
});
